- name: zsh - check if config file exists
  stat:
    path: "{{ ansible_user_dir }}/.zshrc"
  register: zshrc_stat

- name: zsh - backup config file in case there a file already there
  command: >
    mv "{{ ansible_user_dir }}/.zshrc" "{{ ansible_user_dir }}/.zshrc.bak"
  when: zshrc_stat.stat.exists

- name: zsh - create and copy the config file from the template
  template:
    src: .zshrc
    dest: "{{ ansible_user_dir }}/.zshrc"
